# Generated by Django 5.2.7 on 2025-11-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['is_active', '-rating'], name='supplier_active_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['email'], name='supplier_email_idx'),
        ),
    ]
