# Generated by Django 5.2.7 on 2026-01-16 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_supplier_google_maps_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='google_maps_url',
        ),
    ]
