# Generated by Django 5.2.7 on 2026-01-16 15:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0004_remove_customer_google_maps_url'),
        ('orders', '0004_remove_order_order_priority_idx_and_more'),
        ('suppliers', '0004_remove_supplier_google_maps_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsPayable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(help_text='Bill/Invoice number from supplier', max_length=50, unique=True)),
                ('bill_date', models.DateField(help_text='Bill date')),
                ('due_date', models.DateField(help_text='Payment due date')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Bill amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount paid so far', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('balance', models.DecimalField(decimal_places=2, help_text='Outstanding balance', max_digits=12)),
                ('status', models.CharField(choices=[('open', 'Open'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ap_entries', to='orders.order')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ap_accounts', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Accounts Payable',
                'verbose_name_plural': 'Accounts Payable',
                'ordering': ['-bill_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountsReceivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text='Invoice number', max_length=50, unique=True)),
                ('invoice_date', models.DateField(help_text='Invoice date')),
                ('due_date', models.DateField(help_text='Payment due date')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Invoice amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount paid so far', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('balance', models.DecimalField(decimal_places=2, help_text='Outstanding balance', max_digits=12)),
                ('status', models.CharField(choices=[('open', 'Open'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ar_accounts', to='customers.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ar_entries', to='orders.order')),
            ],
            options={
                'verbose_name': 'Accounts Receivable',
                'verbose_name_plural': 'Accounts Receivable',
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Account code (e.g., 1000, 2000)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Account name', max_length=200)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('expense', 'Expense')], help_text='Type of account', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounting.chartofaccounts')),
            ],
            options={
                'verbose_name': 'Chart of Account',
                'verbose_name_plural': 'Chart of Accounts',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current account balance (positive = customer owes, negative = credit)', max_digits=12)),
                ('total_invoiced', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount invoiced', max_digits=12)),
                ('total_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount paid', max_digits=12)),
                ('last_transaction_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Customer Account',
                'verbose_name_plural': 'Customer Accounts',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneralLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(help_text='Date of the transaction')),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Debit amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Credit amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('transaction_type', models.CharField(choices=[('order_created', 'Order Created'), ('customer_payment', 'Customer Payment'), ('supplier_payment', 'Supplier Payment'), ('purchase_order', 'Purchase Order'), ('adjustment', 'Adjustment'), ('other', 'Other')], max_length=30)),
                ('reference', models.CharField(blank=True, help_text='Reference number (e.g., Order #123)', max_length=100)),
                ('description', models.TextField(help_text='Transaction description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gl_entries', to='accounting.chartofaccounts')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_gl_entries', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gl_entries', to='orders.order')),
            ],
            options={
                'verbose_name': 'General Ledger Entry',
                'verbose_name_plural': 'General Ledger Entries',
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('customer_payment', 'Customer Payment'), ('supplier_payment', 'Supplier Payment')], max_length=20)),
                ('payment_date', models.DateField(help_text='Payment date')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('fawry', 'Fawry'), ('vodafone_cash', 'Vodafone Cash'), ('orange_money', 'Orange Money'), ('etisalat_cash', 'Etisalat Cash'), ('paymob', 'Paymob'), ('paytabs', 'PayTabs'), ('myfatoorah', 'MyFatoorah'), ('other', 'Other')], max_length=30)),
                ('reference_number', models.CharField(blank=True, help_text='Payment reference/transaction ID', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ap_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='accounting.accountspayable')),
                ('ar_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='accounting.accountsreceivable')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='orders.order')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='accountspayable',
            index=models.Index(fields=['supplier', 'status'], name='ap_supplier_status_idx'),
        ),
        migrations.AddIndex(
            model_name='accountspayable',
            index=models.Index(fields=['bill_date'], name='ap_bill_date_idx'),
        ),
        migrations.AddIndex(
            model_name='accountspayable',
            index=models.Index(fields=['due_date', 'status'], name='ap_due_date_status_idx'),
        ),
        migrations.AddIndex(
            model_name='accountsreceivable',
            index=models.Index(fields=['customer', 'status'], name='ar_customer_status_idx'),
        ),
        migrations.AddIndex(
            model_name='accountsreceivable',
            index=models.Index(fields=['invoice_date'], name='ar_invoice_date_idx'),
        ),
        migrations.AddIndex(
            model_name='accountsreceivable',
            index=models.Index(fields=['due_date', 'status'], name='ar_due_date_status_idx'),
        ),
        migrations.AddIndex(
            model_name='chartofaccounts',
            index=models.Index(fields=['code'], name='coa_code_idx'),
        ),
        migrations.AddIndex(
            model_name='chartofaccounts',
            index=models.Index(fields=['account_type'], name='coa_type_idx'),
        ),
        migrations.AddIndex(
            model_name='customeraccount',
            index=models.Index(fields=['customer'], name='customer_account_customer_idx'),
        ),
        migrations.AddIndex(
            model_name='customeraccount',
            index=models.Index(fields=['balance'], name='customer_account_balance_idx'),
        ),
        migrations.AddIndex(
            model_name='generalledgerentry',
            index=models.Index(fields=['entry_date'], name='gl_entry_date_idx'),
        ),
        migrations.AddIndex(
            model_name='generalledgerentry',
            index=models.Index(fields=['account', 'entry_date'], name='gl_account_date_idx'),
        ),
        migrations.AddIndex(
            model_name='generalledgerentry',
            index=models.Index(fields=['transaction_type'], name='gl_transaction_type_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='payment_date_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_type'], name='payment_type_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['ar_entry'], name='payment_ar_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['ap_entry'], name='payment_ap_idx'),
        ),
    ]
