# Generated by Django 5.2.7 on 2025-11-28 21:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(help_text='When this token expires')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_password_resets', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, help_text='User who initiated the reset (can be self or admin)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_password_resets', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='password_reset_status_idx'), models.Index(fields=['expires_at'], name='password_reset_expiry_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('SUB_ADMIN', 'Sub Admin'), ('SUPPLIER', 'Supplier'), ('PRODUCT_REQUESTER', 'Product Requester')], default='PRODUCT_REQUESTER', help_text='User role that controls access to system features', max_length=40)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('SUSPENDED', 'Suspended'), ('DISABLED', 'Disabled')], default='ACTIVE', help_text='Lifecycle status for the user account', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Flexible metadata (e.g., supplier category, requester tags)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Administrator who provisioned this account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisioned_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='profile_user_idx'), models.Index(fields=['role'], name='profile_role_idx'), models.Index(fields=['status'], name='profile_status_idx')],
            },
        ),
    ]
