# Generated by Django 5.2.7 on 2025-11-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_customer_phone_idx_and_more'),
        ('orders', '0001_initial'),
        ('suppliers', '0002_supplier_supplier_active_rating_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='order_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', '-created_at'], name='order_customer_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['supplier', 'status'], name='order_supplier_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['delivery_date'], name='order_delivery_date_idx'),
        ),
        migrations.AddIndex(
            model_name='ordermessage',
            index=models.Index(fields=['order', 'created_at'], name='message_order_created_idx'),
        ),
    ]
