# Generated by Django 5.2.7 on 2026-01-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_google_maps_url'),
        ('orders', '0002_order_order_status_created_idx_and_more'),
        ('suppliers', '0003_supplier_google_maps_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_ai_generated',
            field=models.BooleanField(default=False, help_text='Whether this order was automatically generated by AI'),
        ),
        migrations.AddField(
            model_name='order',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Order priority level', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='risk_score',
            field=models.FloatField(default=0.0, help_text='AI-calculated risk score (0.0 to 1.0)'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['priority'], name='order_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['risk_score'], name='order_risk_score_idx'),
        ),
    ]
