# Generated by Django 5.2.7 on 2026-01-16 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_is_ai_generated_order_priority_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='order_priority_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_risk_score_idx',
        ),
    ]
