# Generated by Django 5.2.7 on 2026-01-16 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_order_priority_idx_and_more'),
        ('suppliers', '0004_remove_supplier_google_maps_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_feedback',
            field=models.TextField(blank=True, help_text='Feedback from customer', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_delivered_confirmed',
            field=models.BooleanField(default=False, help_text='Whether customer confirmed delivery'),
        ),
        migrations.CreateModel(
            name='SupplierOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit offered', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount for this offer', max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('waiting_confirmation', 'Waiting Confirmation'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('timeout', 'Timeout')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(help_text='Order this offer is for', on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='orders.order')),
                ('supplier', models.ForeignKey(help_text='Supplier making the offer', on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['unit_price'],
                'unique_together': {('order', 'supplier')},
            },
        ),
    ]
