# Generated by Django 5.2.9 on 2026-01-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_customer_phone_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='google_maps_url',
            field=models.URLField(blank=True, help_text='Google Maps location link', max_length=500, null=True),
        ),
    ]
